In [1]:
import functools as f
from datetime import datetime

from sklearn.cluster import SpectralClustering
from numpy.typing import NDArray
import numpy as np

from common import grid_search, load_data

In [2]:
def get_clusters(
    adj_matrix: NDArray[np.float64 | np.int32], hyperparameters: dict, seed=456
):
    clustering = SpectralClustering(
        n_clusters=hyperparameters["n_clusters"],
        assign_labels=hyperparameters["strategy"],
        random_state=seed,
    ).fit(adj_matrix)

    return clustering.labels_

In [3]:
def generate_hyperparameters_for_sc(max_number_clusters: int):
    combinations = []
    for ncluster in range(2, max_number_clusters + 1):
        for strategy in ["kmeans"]:
            combinations.append(
                {
                    "n_clusters": ncluster,
                    "strategy": strategy,
                }
            )

    return combinations

In [4]:
method = "sc"
dataset = "dwug_es"
path_to_gold_data = "../gold-data-es.csv" 
path_to_data= f"../llama3.3-dwug-es.csv"
max_number_clusters = 5
wic_data = False

In [5]:
metadata = {
    "method": method,
    "dataset": dataset,
    "path_to_data": path_to_data ,
    "path_to_gold_data": path_to_gold_data,
    "fill_diagonal": True,
    "normalize": False,
    "wic_data": wic_data
}

In [6]:
start_time = datetime.now()

grid_search(
    f.partial(load_data, path_to_data),
    get_clusters,
    generate_hyperparameters_for_sc(max_number_clusters=max_number_clusters),
    metadata=metadata,
)

print(f"Elapsed time: {datetime.now() - start_time}")

2026-05-14 21:10:17,468 - INFO - loading data from ../llama3.3-dwug-es.csv ...
2026-05-14 21:10:17,870 - INFO - data loaded ...
2026-05-14 21:10:17,871 - INFO - eval sc method...
2026-05-14 21:10:17,871 - INFO - get predictions ...
2026-05-14 21:10:17,928 - INFO - building adjacency matrix ...
2026-05-14 21:10:17,935 - INFO - adjacency matrix built ...
2026-05-14 21:10:17,935 - INFO - calculating predictions ...


216536
(27067, 8)


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies 
[2.00008565e-15 1.95118060e-07 8.45524777e-06]
not reaching the requested tolerance 5.960464477539062e-07.
Use iteration 1637 instead with accuracy 
1.9587344871322695e-06.

  _, diffusion_map = lobpcg(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies 
[2.16700095e-15 1.96893522e-07 5.67930997e-06]
not reaching the requested tolerance 5.960464477539062e-07.
  _, diffusion_map = lobpcg(
2026-05-14 21:10:21,921 - INFO - building adjacency matrix

Results(jsd=0.22781387210026416, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 18, 1: 2})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,259 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,265 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,265 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,337 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,343 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,343 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklear

Results(jsd=0.05596101549003784, cluster_to_freq1={1: 3, 0: 17}, cluster_to_freq2={1: 4, 0: 16})
Results(jsd=0.28176478092248636, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 17, 1: 3})
Results(jsd=0.3286815269308577, cluster_to_freq1={1: 16, 0: 4}, cluster_to_freq2={1: 20, 0: 0})
Results(jsd=0.22781387210026416, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.09283215667741838, cluster_to_freq1={0: 15, 1: 5}, cluster_to_freq2={0: 13, 1: 7})
Results(jsd=0.3286815269308577, cluster_to_freq1={1: 0, 0: 20}, cluster_to_freq2={1: 4, 0: 16})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,500 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,508 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,508 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,515 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,521 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,521 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklear

Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.0, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.0, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.24698737605160295, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 15, 1: 5})
Results(jsd=0.0643932764095418, cluster_to_freq1={0: 3, 1: 17}, cluster_to_freq2={0: 2, 1: 18})
Results(jsd=0.0, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 19, 1: 1})


2026-05-14 21:10:22,708 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,715 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,723 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,723 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:22,730 - INFO - building adjacency matrix ...
2026-05-14 21:10:22,740 - INFO - adjacency matrix built ...
2026-05-14 21:10:22,740 - INFO - calculating predictions ...
/home/f

Results(jsd=0.740806952380577, cluster_to_freq1={0: 5, 1: 15}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.0643932764095418, cluster_to_freq1={0: 18, 1: 2}, cluster_to_freq2={0: 17, 1: 3})
Results(jsd=0.15371150587860172, cluster_to_freq1={1: 17, 0: 3}, cluster_to_freq2={1: 14, 0: 6})
Results(jsd=0.6303273829919548, cluster_to_freq1={1: 2, 0: 18}, cluster_to_freq2={1: 16, 0: 4})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies 
[9.37346354e-16 9.64866745e-08 5.83961936e-05]
not reaching the requested tolerance 5.960464477539062e-07.
Use iteration 1941 instead with accuracy 
5.6244376417132495e-06.

  _, diffusion_map = lobpcg(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies 
[2.64420521e-15 9.04477518e-08 1.67828648e-05]
not reaching the requested tolerance 5.960464477539062e-07.
  _, diffusion_map = lobpcg(
2026-05-14 21:10:23,071 - INFO - building adjacency matrix ...
2026-05-14 21:10:23,079 - INFO - adjacency matrix built ...
2026-05-14 21:10:23,080 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit`

Results(jsd=0.0643932764095418, cluster_to_freq1={1: 2, 0: 18}, cluster_to_freq2={1: 3, 0: 17})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies 
[4.81488417e-16 1.86002531e-07 2.43092903e-06]
not reaching the requested tolerance 5.960464477539062e-07.
Use iteration 1320 instead with accuracy 
6.747578272258799e-07.

  _, diffusion_map = lobpcg(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies 
[1.88747540e-15 1.64594986e-07 1.85970831e-06]
not reaching the requested tolerance 5.960464477539062e-07.
  _, diffusion_map = lobpcg(
2026-05-14 21:10:23,352 - INFO - building adjacency matrix ...
2026-05-14 21:10:23,364 - INFO - adjacency matrix built ...
2026-05-14 21:10:23,364 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``

Results(jsd=0.08133430256588131, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.042962057701503034, cluster_to_freq1={1: 9, 0: 11}, cluster_to_freq2={1: 8, 0: 12})


2026-05-14 21:10:23,640 - INFO - building adjacency matrix ...
2026-05-14 21:10:23,647 - INFO - adjacency matrix built ...
2026-05-14 21:10:23,648 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:23,738 - INFO - building adjacency matrix ...
2026-05-14 21:10:23,745 - INFO - adjacency matrix built ...
2026-05-14 21:10:23,745 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:23,758 - INFO - building adjacency matrix ...
2026-

Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.3286815269308577, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 16, 1: 4})
Results(jsd=0.7810163551494856, cluster_to_freq1={1: 20, 0: 0}, cluster_to_freq2={1: 4, 0: 16})
Results(jsd=0.28176478092248636, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 17, 1: 3})
Results(jsd=0.0, cluster_to_freq1={1: 14, 0: 6}, cluster_to_freq2={1: 14, 0: 6})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies 
[1.15335244e-12 6.65469653e-08 5.23164249e-06]
not reaching the requested tolerance 5.960464477539062e-07.
Use iteration 1964 instead with accuracy 
3.38539659723507e-07.

  _, diffusion_map = lobpcg(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies 
[4.75359585e-15 6.95810764e-08 9.46036084e-07]
not reaching the requested tolerance 5.960464477539062e-07.
  _, diffusion_map = lobpcg(
2026-05-14 21:10:24,090 - INFO - building adjacency matrix .

Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.08133430256588131, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.08859781384832993, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 17, 1: 2})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})


2026-05-14 21:10:24,404 - INFO - building adjacency matrix ...
2026-05-14 21:10:24,411 - INFO - adjacency matrix built ...
2026-05-14 21:10:24,411 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:24,433 - INFO - building adjacency matrix ...
2026-05-14 21:10:24,441 - INFO - adjacency matrix built ...
2026-05-14 21:10:24,441 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:24,449 - INFO - building adjacency matrix ...
2026-

Results(jsd=0.22781387210026416, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.22781387210026416, cluster_to_freq1={1: 2, 0: 18}, cluster_to_freq2={1: 0, 0: 20})
Results(jsd=0.0, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.1984991617058802, cluster_to_freq1={0: 16, 1: 4}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.28176478092248636, cluster_to_freq1={0: 17, 1: 3}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.08133430256588131, cluster_to_freq1={0: 18, 1: 2}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})


2026-05-14 21:10:24,612 - INFO - adjacency matrix built ...
2026-05-14 21:10:24,612 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:24,619 - INFO - building adjacency matrix ...
2026-05-14 21:10:24,628 - INFO - adjacency matrix built ...
2026-05-14 21:10:24,628 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:24,634 - INFO - building adjacency matrix ...
2026-05-14 21:10:24,641 - INFO - adjacency matrix built ...
2026-05-

Results(jsd=0.22781387210026416, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.4916352242047049, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 9, 1: 11})
Results(jsd=0.05088928511745992, cluster_to_freq1={0: 16, 1: 4}, cluster_to_freq2={0: 15, 1: 5})
Results(jsd=0.1444886247187058, cluster_to_freq1={1: 17, 0: 3}, cluster_to_freq2={1: 19, 0: 1})
Results(jsd=0.1319140868736712, cluster_to_freq1={0: 14, 1: 6}, cluster_to_freq2={0: 11, 1: 9})
Results(jsd=0.4113330221378465, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 14, 1: 6})


2026-05-14 21:10:24,841 - INFO - building adjacency matrix ...
2026-05-14 21:10:24,849 - INFO - adjacency matrix built ...
2026-05-14 21:10:24,849 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,010 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,018 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,018 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,025 - INFO - building adjacency matrix ...
2026-

Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.0, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 19, 1: 1})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,126 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,135 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,136 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(


Results(jsd=0.3286815269308577, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 16, 1: 4})


2026-05-14 21:10:25,344 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,350 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,350 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,453 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,464 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,464 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklear

Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 20, 1: 0}, cluster_to_freq2={0: 19, 1: 1})


2026-05-14 21:10:25,550 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,558 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,568 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,568 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit``now constructs an affinity matrix from data. To use a custom affinity matrix, set ``affinity=precomputed``.
  warnings.warn(
2026-05-14 21:10:25,575 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,581 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,581 - INFO - calculating predictions ...
/home/f

Results(jsd=0.10662495158074255, cluster_to_freq1={1: 17, 0: 3}, cluster_to_freq2={1: 15, 0: 5})
Results(jsd=0.15956958650912217, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 20, 1: 0})
Results(jsd=0.15956958650912217, cluster_to_freq1={1: 0, 0: 20}, cluster_to_freq2={1: 1, 0: 19})
Results(jsd=0.11991021840559969, cluster_to_freq1={1: 18, 0: 2}, cluster_to_freq2={1: 16, 0: 4})


/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited at iteration 2000 with accuracies 
[1.15676501e-12 4.04634912e-07 1.20466582e-05]
not reaching the requested tolerance 5.960464477539062e-07.
Use iteration 1518 instead with accuracy 
3.6235764423587364e-07.

  _, diffusion_map = lobpcg(
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/manifold/_spectral_embedding.py:455: UserWarning: Exited postprocessing with accuracies 
[1.38522135e-14 2.49651494e-07 8.37421134e-07]
not reaching the requested tolerance 5.960464477539062e-07.
  _, diffusion_map = lobpcg(
2026-05-14 21:10:25,948 - INFO - building adjacency matrix ...
2026-05-14 21:10:25,954 - INFO - adjacency matrix built ...
2026-05-14 21:10:25,954 - INFO - calculating predictions ...
/home/fzamora/miniconda3/envs/ex/lib/python3.12/site-packages/sklearn/cluster/_spectral.py:702: UserWarning: The spectral clustering API has changed. ``fit`

Results(jsd=0.08133430256588131, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 18, 1: 2})
Results(jsd=0.08133430256588131, cluster_to_freq1={0: 19, 1: 1}, cluster_to_freq2={0: 18, 1: 2})


AttributeError: 'str' object has no attribute 'mkdir'